name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  contents: read
  secrets: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Credentials
        run: |
            echo "MYSECRET: ${{ secrets.MYSECRET }}"
            echo "DockerHub User: ${{ secrets.DOCKERHUB_USERNAME }}"
            echo "Token starts with: ${DOCKERHUB_TOKEN:0:4}..."

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mt4-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mt4-gateway:${{ github.sha }}